### ISSUE TITLE
Knative SSL with self-signed cert

### ISSUE THREAD

**Issue by cvicens** [alpha-hack-program/doc-bot#1]
https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2-latest/html/serving_models/serving-large-models_serving-large-models#manually-installing-kserve_serving-large-models

Try to use the previous link to use the OCP cert instead of the self signed cert generated during RHOAI installation.

**Comment by rbo** [comment]
Be careful while using the same certificate. In case your application use http2 it can cause weird connections problems: https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/

**Comment by cvicens** [comment]
Thanks Robert for jumping in!! Just to clarify, I want to use a proper cert, Let's encrypt for instance and not a self signed one. I wanted to reuse the wildcard cert of OCP... but it could be different if there could be potential problems like the ones you pointed out when mixing http/1 and /2... Have you done this once knative-serving has been created with a self-signed cert?

**Comment by rbo** [comment]
Long time ago at RH Training 3-4 Years ago...

**Comment by cvicens** [comment]
No prob ! Thanks any way Robert!!!

**Comment by cvicens** [comment]
Solved with this: https://ai-on-openshift.io/odh-rhoai/single-stack-serving-certificate/
